### PR TITLE
Make symfony/thanks a suggestion rather than a hard requirement

### PR DESCRIPTION
**Pull request by pfrenssen**
Fix for #3788

### CODE REVIEW

**Comment by nicolas-grekas** [comment]
This doesn't provide the same experience at all.
symfony/thanks is a requirement to the experience the authors of drupal-console want to provide out of the box. Thus it belongs to "require". I understand that you have a different definition of what "require" means, but there is nothing anywhere that makes your definition more accurate than this definition given here: a requirement to the experience. That's a great thing.

**Comment by dkarlovi** [comment]
Perhaps a better project to provide that experience would be Composer? This avoids needing to do it for each and every project separately.

**Comment by nicolas-grekas** [comment]
@dkarlovi see https://github.com/symfony/thanks/issues/35

**Comment by dkarlovi** [comment]
@nicolas-grekas yeah, I've seen that issue / tweet before. My point is, if Composer doesn't want to have it be part of their default experience (where it IMO makes way more sense), why should random projects?

Not trying to imply the intention is bad in any way, on the contrary. Just think that adding a Composer plugin as a **base requirement** to random projects is not a good way forward from a technical standpoint.

**Comment by nicolas-grekas** [comment]
> Composer doesn't want to have it be part of their default experience

that's certainly not the reason why this is not in Composer. The only reason that is in this tweet in the maintenance burden this would create on Composer. That's a perfectly valid point. I'm way more interested in maintaining this plugin myself, so that Composer guys can focus their time on core Composer features.

**Comment by dkarlovi** [comment]
> maintenance burden this would create on Composer

That's "Composer doesn't want it" said in a different way. :smile: 

How do you reconcile advocating to add this here as `require` while [Symfony doesn't `require-dev` code it actually references](https://github.com/symfony/symfony/pull/25536#discussion_r157591181)? Seems like a double standard.

Anyway, I understand you're on a mission to get this across (and IMO it a valuable cause), but still think there's got to be a better way to do this.

**Comment by davereid** [comment]
There's no way to disable the message. I'm seeing it every time that composer update pulls in new packages, and for a large project that is often. I get it, but now I have no way to NOT see it.

**Comment by jmolivas** [comment]
@pfrenssen Thanks for your contribution, your PR was merged. This will be included in the next release.

**Comment by pfrenssen** [comment]
Thanks!

**Pull request merged**
