### PR TITLE
[module:install] Allow module installation with Drupal 8.8.x and enable Composer-based installation

### LINKED ISSUE #4166: [module:install] Module installation fails with Drupal 8.8.x and contrib modules specifiying 'core_version_requirement' in .info.yml
The commit in Drupal 8.8.x of [Core version key in module's .info.yml doesn't respect core semantic versioning](https://www.drupal.org/project/drupal/issues/2313917) introduced a new `core_version_requirement` key in the module.info.yml files.

Using Drupal console to install a contrib module that supplies the new key only, without the legacy `core` key, fails.

`$ drupal module:install imagemagick --verbose --no-interaction
 ✘ This version is not compatible with Drupal 8.x and should be replaced.
 ✘ File metadata manager incompatible with this version of Drupal core.
In InstallCommand.php line 315:
                                                 
  [Exception]                                    
  Some module install requirements are not met.  
                                                 
Exception trace:
 () at /home/travis/drupal8/vendor/drupal/console/src/Command/Module/InstallCommand.php:315
 Drupal\Console\Command\Module\InstallCommand->moduleRequirement() at /home/travis/drupal8/vendor/drupal/console/src/Command/Module/InstallCommand.php:152
 Drupal\Console\Command\Module\InstallCommand->execute() at /home/travis/drupal8/vendor/symfony/console/Command/Command.php:255
 Symfony\Component\Console\Command\Command->run() at /home/travis/drupal8/vendor/symfony/console/Application.php:978
 Symfony\Component\Console\Application->doRunCommand() at /home/travis/drupal8/vendor/symfony/console/Application.php:255
 Symfony\Component\Console\Application->doRun() at /home/travis/drupal8/vendor/drupal/console-core/src/Application.php:188
 Drupal\Console\Core\Application->doRun() at /home/travis/drupal8/vendor/drupal/console/src/Application.php:64
 Drupal\Console\Application->doRun() at /home/travis/drupal8/vendor/symfony/console/Application.php:148
 Symfony\Component\Console\Application->run() at /home/travis/drupal8/vendor/drupal/console/bin/drupal.php:89
 require() at /home/travis/drupal8/vendor/drupal/console/bin/drupal:4
module:install [--latest] [--composer] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--env [ENV]] [--root [ROOT]] [--debug] [--learning] [-c|--generate-chain] [-i|--generate-inline] [-d|--generate-doc] [-t|--target [TARGET]] [-l|--uri URI] [-y|--yes] [--] <command> [<module>].`

### PR DESCRIPTION
**Pull request by mondrake**
This PR fixes #4166 and allows to use the `--composer` option in module:install.

Adds some demonstration of that in TravisCI: the Imagemagick module in dev-3.x adheres strictly to the `core_version_requirement` syntax, so here the TravisCI build shows how to download that module (together with others) with the --composer option and get it installed.

Note that using the --composer option you can also use Composer syntax with constraints to specify the module to be installed. The four examples below are equivalent:

`$ drupal module:install --composer token`

`$ drupal module:install --composer token:^1`

`$ drupal module:install --composer drupal/token`

`$ drupal module:install --composer "drupal/token:^1"`

### CODE REVIEW

**Comment by enzolutions** [comment]
@mondrake why the --composer is not possible in version 8.7.7 and lowers?

I am a little hesitant and include in the code validation for specific versions.

**Comment by mondrake** [comment]
@enzolutions actually —composer is working ALWAYS with this PR. You can see that in the TravisCI runs for PHP 5.5 and 5.6, wher Drupal 8.6 is installed 😃

What becomes version dependent with this PR is the call to moduleRequirements that uses old APIs. Actually I believe that entire method is redundant, since Drupal module installer service just performs the same checks. 

I would remove it, but prefer to do so in a separate PR

**Comment by enzolutions** [comment]
So, you plan to merge this PR and in the next one remove the redundancy?

**Comment by mondrake** [comment]
yes. later on, there’s also work to do for module update to match what we are doing in module install

**Comment by mondrake** [comment]
@enzolutions - if you want, take a look at mondrake/drupal-console:dev-moi-modulereq-remove for a change that includes both this PR and the removal of the `moduleRequirement` method. I can submit it as a PR if you want to make a bigger jump. TravisCI passes on that one, too.

https://github.com/hechoendrupal/drupal-console/compare/master...mondrake:dev-moi-modulereq-remove?expand=1

**Comment by enzolutions** [comment]
OK, but the other link, doesn't include the removal of this code

```
 if (version_compare(\Drupal::VERSION, '8.7.7') < 0) {
            $this->moduleRequirement($module);
        }
```

**Comment by mondrake** [comment]
😀 because in the other link it never gets there vs current HEAD

**Comment by mondrake** [comment]
sorry if I confused more than clarified... with this PR the call is conditional based on Drupal bersion. With the other link the call and methid are removed.

if this PR gets merged, then the following PR will remove the if... and the call inside.

**Comment by enzolutions** [comment]
done @mondrake

**Pull request merged**
