### PR TITLE
[theme] Refactor theme commands. Fix #3696

### LINKED ISSUE #3696: Refactor [theme:install] and [theme:uninstall]
### Issue
Both commands have a lot of code in common

### Problem/Motivation
Improve the code base

### Solution
Create a base class and move common code there

### PR DESCRIPTION
**Pull request by LOBsTerr**
1) Created the base class
2) Created the methods to display info and error messages 
3) Created the methods handling available, unavailable and uninstalled themes
4) Created the common method to get theme argument 
5) And other improvements, which simplify the main logic and remove duplications

### CODE REVIEW

**Comment by jmolivas** [comment]
@LOBsTerr is this ready to be tested or still WIP?

**Comment by LOBsTerr** [comment]
@jmolivas It is finished. You can test it

**Comment by jmolivas** [comment]
@LOBsTerr cold you sync with the master branch?

**Comment by LOBsTerr** [comment]
@jmolivas All conflicts have been resolved.

**Comment by jmolivas** [comment]
@LOBsTerr Thanks for your contribution, your PR was merged. This will be included in the next release.

**Pull request merged**
