### PR TITLE
[debug:theme:keys] Displays all theme keys for DX.

### PR DESCRIPTION
**Pull request by DuaelFr**

### CODE REVIEW

**Comment by DuaelFr** [comment]
Translations:
- EN https://github.com/hechoendrupal/drupal-console-en/pull/89
- FR https://github.com/hechoendrupal/drupal-console-fr/pull/10

**Comment by DuaelFr** [comment]
Code rebased on the last commit

**Comment by bonfil1** [comment]
While testing this the outcome:

`ArgumentCountError: Too few arguments to function block_content_theme(), 0 passed and exactly 4 expected in /var/www/drupalvm/drupal/site/web/core/modules/block_content/block_content.module on line 45 #0 [internal function]: block_content_theme()
#1 /var/www/drupalvm/drupal/site/web/core/lib/Drupal/Core/Extension/ModuleHandler.php(391): call_user_func_array('block_content_t...', Array)
#2 /var/www/drupalvm/drupal/drupal-console/src/Command/Theme/DebugKeysCommand.php(60): Drupal\Core\Extension\ModuleHandler->invoke('block_content', 'theme')
#3 /var/www/drupalvm/drupal/drupal-console/src/Command/Theme/DebugKeysCommand.php(47): Drupal\Console\Command\Theme\DebugKeysCommand->themeKeysList(Object(Drupal\Console\Core\Style\DrupalStyle))
#4 /var/www/drupalvm/drupal/site/vendor/symfony/console/Command/Command.php(266): Drupal\Console\Command\Theme\DebugKeysCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#5 /var/www/drupalvm/drupal/site/vendor/symfony/console/Application.php(874): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 /var/www/drupalvm/drupal/site/vendor/symfony/console/Application.php(203): Symfony\Component\Console\Application->doRunCommand(Object(Drupal\Console\Command\Theme\DebugKeysCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#7 /var/www/drupalvm/drupal/site/vendor/drupal/console-core/src/Application.php(118): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 /var/www/drupalvm/drupal/drupal-console/src/Application.php(71): Drupal\Console\Core\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 /var/www/drupalvm/drupal/site/vendor/symfony/console/Application.php(127): Drupal\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 /var/www/drupalvm/drupal/drupal-console/bin/drupal.php(84): Symfony\Component\Console\Application->run()
#11 /var/www/drupalvm/drupal/drupal-console/bin/drupal(4): require('/var/www/drupal...')
#12 {main}
ArgumentCountError: Too few arguments to function block_content_theme(), 0 passed and exactly 4 expected in block_content_theme() (line 45 of /var/www/drupalvm/drupal/site/web/core/modules/block_content/block_content.module).`

Args tested:

drupal theme:keys:debug --ansi
drupal theme:keys:debug --debug
drupal theme:keys:debug --generate-doc
drupal theme:keys:debug --generate-chain

**Comment by jmolivas** [comment]
@DuaelFr I had a similar error
```
drupal theme:keys:debug
ArgumentCountError: Too few arguments to function block_content_theme(), 
0 passed and exactly 4 expected in block_content_theme() (line 45 of /Users/jmolivas/develop/drupal/sites/drupal.dev/web/core/modules/block_content/block_content.module).
```

**Comment by DuaelFr** [comment]
Thank you for your feedback.
I had some issues to be able to test what I developped in a real project but I finally found a way.
I updated the PR to fix the command and improve it. I moved it to the right namespace and added an optional argument so it can provide more details if needed.

**Comment by DuaelFr** [comment]
@jmolivas I don't know if it's normal that this issue still have the "Needs work" label or not. It's done for me, let me know if I can do anything else to move it forward.

**Comment by jmolivas** [comment]
@DuaelFr can you provide some examples about how to test it.

**Comment by DuaelFr** [comment]
List all theme keys available for the installed site (defined by all active hook_theme implementations).
$ drupal dtk

Display details (e.g. variables) for a given theme key
$ drupal dtk item_list

**Comment by jmolivas** [comment]
@DuaelFr  Tested and it works properly.

**Comment by jmolivas** [comment]
@DuaelFr  Thanks for your contribution, your PR was merged. This will be included in the next release.

**Comment by DuaelFr** [comment]
Thank YOU for all your contributions and support :)

**Pull request merged**
