### PR TITLE
[config:export:content:type] Fixed conflicts and add missing services

### PR DESCRIPTION
**Pull request by harold20**
This PR is an extension of https://github.com/hechoendrupal/drupal-console/pull/3846 and resolved missing code and conflicts

### CODE REVIEW

**Comment by LOBsTerr** [comment]
@enzolutions I have reverted my changes, which uses "config:export:entity" as chain command.
I have added it. In order to reduce duplication and make it more easier to export any entity.

```
$this->chainQueue->addCommand(
            'config:export:entity', [
                'entity-type' => 'node_type',
                'bundle' => $contentType,
                '--module' => $module,
                '--optional-config' => $optionalConfig,
                '--remove-uuid' => $removeUuid,
                '--remove-config-hash' => $removeHash
            ]
        );
```

**Comment by enzolutions** [comment]
Hi, @LOBsTerr Do you mean we need to revert this merge? and you will create another PR to introduce your suggestion?

**Comment by LOBsTerr** [comment]
I will create a new pr, with the current improvements and my changes

**Comment by enzolutions** [comment]
Awesome @LOBsTerr

**Comment by LOBsTerr** [comment]
@enzolutions Everything should be here: https://github.com/hechoendrupal/drupal-console/issues/4044

 More information in my new PR: https://github.com/hechoendrupal/drupal-console/pull/4045

**Comment by enzolutions** [comment]
Awesome, we will review an merge soon

**Pull request merged**
