### PR TITLE
New devel:service command

### PR DESCRIPTION
**Pull request by vorapoap**
Usage example
1. "drupal devel:service database" to list available public function and parameters in \Drupal::service('database')
2. "drupal devel:service [yourservice] [yourfunction] [parameters in json,csv] to test your function from command line

### CODE REVIEW

**Comment by jmolivas** [comment]
@vorapoap Thanks for your contribution. We had the `container:debug` command already as pasrt of DrupalConsole and this command can:
1) List all the services on the container:
2) Receive a service name argument an show:

container-debug

Do you see that any of the functionality added in the new command on this PR could be relocated the the current command?

**Comment by vorapoap** [comment]
I just know this.. 
And yes, I can merge the code...

But my ServiceCommand can actually invoke the method inside the service. 
And on listing it also show method's parameters
However, could you tell me why it is called "container:debug"... ?
Does this name make a better sense ?

**Comment by jmolivas** [comment]
@vorapoap 

* But my ServiceCommand can actually invoke the method inside the service.
And on listing it also show method's parameters
> This is the improvement feature will be great to add to current command.

* However, could you tell me why it is called "container:debug"... ?
> This command is similar and inspired on the one you can find using the Symfony framework, since we are using same `symfony/console` component we decided to name it the same. 

* Does this name make a better sense ?
> It make sense, because is replicating  functionality of the command with same name at the SymfonyFramework and because services are registered on the container.

**Comment by vorapoap** [comment]
## Improvement
 * ServiceList is now sorted by alphabet
 * Added color to ServiceDetail, ServiceList
 * Ability to execute method in service along with argument (in CSV,JSON) and see returned variable 

image
image

**Comment by vorapoap** [comment]
image
jmolivas what is this error about?..

**Comment by jmolivas** [comment]
@vorapoap That looks really nice

**Comment by jmolivas** [comment]
@vorapoap I tested this PR and I am getting this error:

```
> drupal container:debug console.about

PHP Fatal error:  Call to undefined method ReflectionParameter::hasType() in /Users/jmolivas/develop/drupal/modules/drupal-console/src/Command/ContainerDebugCommand.php on line 224

Fatal error: Call to undefined method ReflectionParameter::hasType() in /Users/jmolivas/develop/drupal/modules/drupal-console/src/Command/ContainerDebugCommand.php on line 224
```

**Comment by vorapoap** [comment]
That is for PHP7+ only.. so..unfortunately.. I think you can't get parameter type if you are using PHP5.x

**Comment by vorapoap** [comment]
image
You will not get anything in white color.

**Comment by jmolivas** [comment]
@vorapoap thanks for the update I will test and add a comment.

**Comment by vorapoap** [comment]
You'd better release rc18 soon.. the last rc17 version is broken due to the develop.yml containing missing ServiceCommand file

**Comment by jmolivas** [comment]
@vorapoap this look awesome. Thanks for the PR and all of the work.

container-debug

**Comment by jmolivas** [comment]
@vorapoap Thanks for your contribution, your PR was merged. This will be included on the next release.

**Pull request merged**
