### PR TITLE
Added Paragraph type export command

### PR DESCRIPTION
**Pull request by joe-mcpherson**
Added Paragraph type export to export Paragraph type's fields with following command:

drupal config:export:paragraph:type

(Translation in separate pull request on drupal-console-en repository)

### CODE REVIEW

**Comment by LOBsTerr** [comment]
@jmolivas I propose universal solution https://github.com/hechoendrupal/drupal-console/pull/3875. This will reduce amount of code we have to support. (https://github.com/hechoendrupal/drupal-console/issues/3794)

If we still need export of entity as separate command we should use chain instead, but still I don't think it will be useful, if we have a generic command

**Comment by joe-mcpherson** [comment]
@LOBsTerr I agree a generic solution makes more sense. I didn't see your proposal, I just needed this for a project I was working on so thought I'd throw it back if it could be useful for someone

**Comment by jmolivas** [comment]
@LOBsTerr I have to say I like those commands to export configurations and use the result on a custom profile.

I also agree a generic solution one single command could be easy to maintain since is one command but maybe the code gets a little complex since is taking a lot of considerations.

**Comment by LOBsTerr** [comment]
@jmolivas I'm absolutely agree with and in fact I have just a little bit extended the current code and I moved the common classes to the trait ExportTrait.php. Check the PR https://github.com/hechoendrupal/drupal-console/pull/3875/files

**Comment by anuragshah17** [comment]
@joe-mcpherson Hey i am trying to apply patch for this pull, not working with Drupal Console 1.0.1 version. I need to try this with dev version for Drupal Console?

**Comment by anuragshah17** [comment]
@joe-mcpherson Please ignore above message. Command worked with 1.8.0 version. 
Thanks

**Comment by LOBsTerr** [comment]
I was thinking why we limit us only to specific config entities and I added a new commit, which expose all config entities, because I have seen recently request about media type also. Please, test it https://github.com/hechoendrupal/drupal-console/pull/3875

**Comment by LOBsTerr** [comment]
I have merged https://github.com/hechoendrupal/drupal-console/pull/3875
There you can export any config entity

**Pull request merged**
