### PR TITLE
Fix TravisCI testing

### PR DESCRIPTION
**Pull request by mondrake**
As far as I can see, the TravisCI build are actually not performing any testing.

This PR:

- fixes running test for all PHP versions
- performs a Drupal site installation test and site status report by
  - git cloning Drupal core
  - performing `composer install` of Drupal core
  - requesting `drupal/console` via Composer 
  - performing `drupal site:install`
  - performing `drupal site:status`

This is obviously just my workflow... but it seems to work.

### CODE REVIEW

**Comment by enzolutions** [comment]
Thank you @mondrake

**Comment by mondrake** [comment]
Thanks :) 

We need one more tweak, I'll post a new PR

**Comment by enzolutions** [comment]
Sure, just let me know and thanks for your help

**Comment by mondrake** [comment]
See #4137

**Pull request merged**
