### PR TITLE
Generate revisional entity content is broken

### PR DESCRIPTION
**Pull request by clemens-tolboom**
This lack of ; was introduced in dd6492237

### CODE REVIEW

**Comment by enzolutions** [comment]
@clemens-tolboom this is ready to test?

**Comment by clemens-tolboom** [comment]
> @clemens-tolboom this is ready to test?

? ... we just need the semi-colon back right?

**Comment by enzolutions** [comment]
Sure, I just want to confirm, there is nothing else pending to commit, we will check and merge soon.

Thanks for your contributions.

**Comment by clemens-tolboom** [comment]
Are there tests available (for checking generated code)? ... I'm just busy doning #4138 :-)

**Comment by enzolutions** [comment]
Sadly, we don't have support for that kind of tests :S

**Comment by clemens-tolboom** [comment]
@enzolutions I tried to test through #3939 ... can you help with that?

**Comment by enzolutions** [comment]
Thanks @clemens-tolboom

**Pull request merged**
