### PR TITLE
[BUGFIX #2792] root paramater doesn't work

### PR DESCRIPTION
**Pull request by mickaelperrin**
- PB: current script assumes that drupal is run inside the drupal document root before reading the root parameter.
- FIX: 
- autodiscover the autoload file by getting the vendor path
- load the autoload
- read the root parameter

### CODE REVIEW

**Comment by jmolivas** [comment]
@mickaelperrin  I will like to try this for next release. Can you sync with latest changes?

**Comment by mickaelperrin** [comment]
@jmolivas Forgot to warn you that I synced the PR with the latest master.

**Comment by jmolivas** [comment]
Sorry I sent another PR and the file changed again

**Comment by mickaelperrin** [comment]
@jmolivas I updated to the latest master, the support for `root` parameter is now very simple.

However, I still experience the issue #2581 and I am unable to get `drupalconsole`working...

**Comment by jmolivas** [comment]
Still not clear for me why this is happening.

Are you installing DrupalConsole globally using `composer global require` ?

**Comment by jmolivas** [comment]
@mickaelperrin are you still having this issue?

**Comment by jmolivas** [comment]
@mickaelperrin This was fixed to provide a better support for remote commands.

Closing this one. Feel free to re-open if still happening after updating to the latest version.

**Pull request closed without merging**
