### PR TITLE
[site:status] improvements

### PR DESCRIPTION
**Pull request by mondrake**
1. I find the current output of ss a bit too verbose - greatly prefer the more succint results in 1.8.0. So I am proposing to print out the description only if verbose mode is on i.e. the -v flag is set -> `drupal site:status -v`
2. Color coding errors and warnings according to severity of the requirement. This makes ss consistent with Drupal core's 'Status report' webpage.
3. Skip reporting empty keys in the database connection options.

See new results below (non-verbose)
Schermata 2019-05-24 alle 21 27 07

### CODE REVIEW

**Comment by enzolutions** [comment]
@mondrake this is ready to review, to see if we could include in the next release 1.9.0 next week?

**Comment by mondrake** [comment]
yea, no more changes from my side

**Comment by mondrake** [comment]
Done, thanks for review @harold20

**Comment by mondrake** [comment]
Please see also https://github.com/hechoendrupal/drupal-console-en/pull/233

**Comment by harold20** [comment]
Hey @mondrake that new commit has problems related with the "if", You forget close the condition. Could you fix it?

**Comment by mondrake** [comment]
Sorry. Fixed and did a bit more cleaning.

**Comment by enzolutions** [comment]
Thanks @mondrake

**Pull request merged**
