### PR TITLE
[TravisCI] Create a local mirror Composer repository to load drupal/console from the git clone

### PR DESCRIPTION
**Pull request by mondrake**
We can do better here in order to allow Composer requiring drupal/console from the git cloned source - this will also allow taking into account any change in dependencies in composer.json in PRs.

Will help to demonstrate #4077, too!

### CODE REVIEW

**Comment by enzolutions** [comment]
@mondrake this is ready to merge?

**Comment by mondrake** [comment]
@enzolutions yes go ahead :)

Now watch #4077 for the next commit in a few minutes and see the output of `site:status` with the PR applied!

**Comment by enzolutions** [comment]
OK, I will merge, and the other PR we will check-in coming weeks and include in Septembre release 1.9.3.

If you don't notice we release 1.9.2 yesterday, BTW you can subscribe to the Drupalconsole newsletter in our website https://drupalconsole.com

**Comment by mondrake** [comment]
Thanks @enzolutions, I did notice 1.9.2 :)

**Pull request merged**
